### ISSUE TITLE
Published date displayed

### ISSUE THREAD

**Issue by gnott** [elifesciences/lens-browser#28]
Hope this is ok place to raise an issue. 

On http://cdn.substance.io/lens-browser/#state=main;0.searchQuery=%7B%22searchStr%22%3A%2200013  has published on Sun Oct 14 2012

http://lens.elifesciences.org/00013/   has Mon, 15 Oct 2012

**Comment by JGilbert-eLife** [comment]
I'm just adding what looks like another example of this problem:

Article 05959 was published on 15 April 2015 and this is the date present in the XML. However, on Lens (http://lens.elifesciences.org/05959/) the publication date is showing as 14 April 2015.

I'm assuming this issue is still ongoing as http://lens.elifesciences.org/00013/ is showing 14 October 2012 but was published on 15 October 2012!

Let me know if you need any more information. Thanks!

**Comment by sparker88** [comment]
Just throwing a few more examples here - these are all recently published corrections, all of which are showing publication dates of a day before on Lens. 

Thanks!

Article 08843:
![8843_2](https://cloud.githubusercontent.com/assets/8616985/7865084/21682976-055e-11e5-94fe-3843a7e8844d.png)

![8843_1](https://cloud.githubusercontent.com/assets/8616985/7865085/216e747a-055e-11e5-9abc-183c3c603b12.png)

Article 08658:
![8658_1](https://cloud.githubusercontent.com/assets/8616985/7865103/3a2136e2-055e-11e5-851e-14434e1a2aed.png)

![8658_2](https://cloud.githubusercontent.com/assets/8616985/7865129/69ff3b84-055e-11e5-9be7-8a7e52b35c30.png)

Article 08656:
![8656_1](https://cloud.githubusercontent.com/assets/8616985/7865133/6c8e71c6-055e-11e5-8128-6e01d2abf8f5.png)

![8656_2](https://cloud.githubusercontent.com/assets/8616985/7865135/6e68c76c-055e-11e5-9c18-8ae3852363bb.png)

**Comment by michael** [comment]
Will be taken care of until end of June.
